[package]
name = "oosikle"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
serde = "1.0.218"
tokio = { version = "1.43.0", features = ["full"] }
mlua = { version = "0.10", features = ["lua54", "vendored", "send", "serialize"] }
